# BYOL e100 — EchoNet-Dynamic LVEF pred-avg on TEST set
app: vjepa
cpus_per_task: 32
folder: /home/sagemaker-user/user-default-efs/vjepa2/evals/vitl/icml/echobyol_e100_end_lvef_224
mem_per_gpu: 80G
nodes: 1
tasks_per_node: 8
num_workers: 8

eval_name: video_classification_frozen
val_only: true
resume_checkpoint: true
probe_checkpoint: /home/sagemaker-user/user-default-efs/vjepa2/evals/vitl/icml/echobyol_e100_end_lvef_224/video_classification_frozen/icml-echobyol-l-e100-end-lvef-d4/best.pt
tag: icml-echobyol-l-e100-end-lvef-d4-predavg

experiment:
  classifier:
    task_type: regression
    num_heads: 16
    num_probe_blocks: 4
    num_targets: 1

  data:
    dataset_type: VideoDataset
    dataset_train: /home/sagemaker-user/user-default-efs/vjepa2/data/csv/echonet_dynamic_train_local_raw.csv
    dataset_val: /home/sagemaker-user/user-default-efs/vjepa2/data/csv/echonet_dynamic_test_s3_raw.csv
    target_mean: 55.7776
    target_std: 12.4072
    resolution: 224
    frames_per_clip: 16
    frame_step: 2
    num_segments: 2
    num_views_per_segment: 1
    study_sampling: false

  optimization:
    batch_size: 1
    val_batch_size: 64
    num_epochs: 1
    use_bfloat16: true
    use_pos_embed: false
    multihead_kwargs:
    - {final_lr: 0.0, final_weight_decay: 0.01, lr: 0.0001, start_lr: 0.0001, warmup: 0.0, weight_decay: 0.01}
    - {final_lr: 0.0, final_weight_decay: 0.1,  lr: 0.0001, start_lr: 0.0001, warmup: 0.0, weight_decay: 0.1}
    - {final_lr: 0.0, final_weight_decay: 0.4,  lr: 0.0001, start_lr: 0.0001, warmup: 0.0, weight_decay: 0.4}
    - {final_lr: 0.0, final_weight_decay: 0.01, lr: 0.00005, start_lr: 0.00005, warmup: 0.0, weight_decay: 0.01}
    - {final_lr: 0.0, final_weight_decay: 0.1,  lr: 0.00005, start_lr: 0.00005, warmup: 0.0, weight_decay: 0.1}
    - {final_lr: 0.0, final_weight_decay: 0.4,  lr: 0.00005, start_lr: 0.00005, warmup: 0.0, weight_decay: 0.4}

model_kwargs:
  checkpoint: /home/sagemaker-user/user-default-efs/vjepa2/checkpoints/byol_vitl_imagenet_v2_e100.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: target_encoder
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
