app: vjepa
cpus_per_task: 32
folder: /home/sagemaker-user/user-default-efs/vjepa2/evals/vitg-384/kinetics_a4c_pacemaker
mem_per_gpu: 80G
nodes: 1
tasks_per_node: 8
num_workers: 8

eval_name: video_classification_frozen
resume_checkpoint: false # changed from true
tag: kinetics-vitg16-336-16x1x1-16f-h4

experiment:
  classifier:
    num_heads: 16
    num_probe_blocks: 4
    
  data:
    dataset_type: VideoDataset  
    dataset_train: /home/sagemaker-user/user-default-efs/vjepa2/data/a4c_pacemaker_labels_train_tiny.csv
    dataset_val: /home/sagemaker-user/user-default-efs/vjepa2/data/a4c_pacemaker_labels_val_tiny.csv
    num_classes: 2
    resolution: 336  
    frames_per_clip: 16  # cooldown trained on 16 
    frame_step: 3 # fps: 24 # changed from frame_step: 4  
    num_segments: 2  # temporal sampling; how many clips from each video; changed from 8
    num_views_per_segment: 3 # spatial sampling; how many crops from each video; changed from 3 
    
  optimization:
    batch_size: 1
    multihead_kwargs:
      # WD = 0.0
      - lr: 0.001
        start_lr: 0.001
        warmup: 0.1
        weight_decay: 0.0
        final_lr: 0.0
        final_weight_decay: 0.0
      - lr: 0.0003
        start_lr: 0.0003
        warmup: 0.1
        weight_decay: 0.0
        final_lr: 0.0
        final_weight_decay: 0.0
      - lr: 0.0001
        start_lr: 0.0001
        warmup: 0.1
        weight_decay: 0.0
        final_lr: 0.0
        final_weight_decay: 0.0
      - lr: 0.00005
        start_lr: 0.00005
        warmup: 0.1
        weight_decay: 0.0
        final_lr: 0.0
        final_weight_decay: 0.0
      - lr: 0.00001
        start_lr: 0.00001
        warmup: 0.1
        weight_decay: 0.0
        final_lr: 0.0
        final_weight_decay: 0.0
      # WD = 1e-3
      - lr: 0.001
        start_lr: 0.001
        warmup: 0.1
        weight_decay: 0.001
        final_lr: 0.0
        final_weight_decay: 0.001
      - lr: 0.0003
        start_lr: 0.0003
        warmup: 0.1
        weight_decay: 0.001
        final_lr: 0.0
        final_weight_decay: 0.001
      - lr: 0.0001
        start_lr: 0.0001
        warmup: 0.1
        weight_decay: 0.001
        final_lr: 0.0
        final_weight_decay: 0.001
      - lr: 0.00005
        start_lr: 0.00005
        warmup: 0.1
        weight_decay: 0.001
        final_lr: 0.0
        final_weight_decay: 0.001
      - lr: 0.00001
        start_lr: 0.00001
        warmup: 0.1
        weight_decay: 0.001
        final_lr: 0.0
        final_weight_decay: 0.001
      # WD = 1e-2
      - lr: 0.001
        start_lr: 0.001
        warmup: 0.1
        weight_decay: 0.01
        final_lr: 0.0
        final_weight_decay: 0.01
      - lr: 0.0003
        start_lr: 0.0003
        warmup: 0.1
        weight_decay: 0.01
        final_lr: 0.0
        final_weight_decay: 0.01
      - lr: 0.0001
        start_lr: 0.0001
        warmup: 0.1
        weight_decay: 0.01
        final_lr: 0.0
        final_weight_decay: 0.01
      - lr: 0.00005
        start_lr: 0.00005
        warmup: 0.1
        weight_decay: 0.01
        final_lr: 0.0
        final_weight_decay: 0.01
      - lr: 0.00001
        start_lr: 0.00001
        warmup: 0.1
        weight_decay: 0.01
        final_lr: 0.0
        final_weight_decay: 0.01
      # WD = 0.1
      - lr: 0.0003
        start_lr: 0.0003
        warmup: 0.1
        weight_decay: 0.1
        final_lr: 0.0
        final_weight_decay: 0.1
      - lr: 0.0001
        start_lr: 0.0001
        warmup: 0.1
        weight_decay: 0.1
        final_lr: 0.0
        final_weight_decay: 0.1
      - lr: 0.00005
        start_lr: 0.00005
        warmup: 0.1
        weight_decay: 0.1
        final_lr: 0.0
        final_weight_decay: 0.1
      - lr: 0.00001
        start_lr: 0.00001
        warmup: 0.1
        weight_decay: 0.1
        final_lr: 0.0
        final_weight_decay: 0.1

    num_epochs: 20
    use_bfloat16: true
    use_pos_embed: false
model_kwargs:
  checkpoint: /home/sagemaker-user/user-default-efs/vjepa2/checkpoints/vitg-384.pt #  /home/sagemaker-user/user-default-efs/vjepa2/checkpoints/vitg-384.pt / /home/sagemaker-user/user-default-efs/vjepa2/checkpoints/anneal/1.8.vitg16-336px-16f-echo/e21.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: target_encoder
      img_temporal_dim_size: null
      model_name: vit_giant_xformers
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
